<?php
/**
* Magento
*
* NOTICE OF LICENSE
*
* This source file is subject to the Open Software License (OSL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/osl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to license@magentocommerce.com so we can send you a copy immediately.
*
* @category   Phoenix
* @package    Phoenix_CashOnDelivery
* @copyright  Copyright (c) 2010 - 2013 PHOENIX MEDIA GmbH (http://www.phoenix-media.eu)
* @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/
?>
<?php if ($this->getSource()) :?>
<tr>
    <td class="label"><?php echo $this->getRefundLabel(); ?></td>
    <td><input type="text" name="creditmemo[cashondelivery_amount]" value="<?php echo $this->getCodAmount()?>" class="input-text not-negative-amount" style="width:60px;text-align:right" id="cod_amount" /></td>
</tr>
<?php endif; ?>
